// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ExpressTravelCustomerWebAPI.Models
{
    public partial class Contact
    {
        [Key]
        public int ContactId { get; set; }
        public int SalutationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? Dob { get; set; }
        public bool IsStaff { get; set; }

        public virtual Reference Salutation { get; set; }
    }
}