// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExpressTravelCustomerWebAPI.Models
{
    public partial class Reference
    {
        public Reference()
        {
            Contacts = new HashSet<Contact>();
        }

        public int ReferenceId { get; set; }
        public string RefType { get; set; }
        public string RefText { get; set; }

        public virtual ICollection<Contact> Contacts { get; set; }
    }
}